/* Generated by Yosys 0.9+4052 (git sha1 a5adb007, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module circ(a, b, r);
  wire \U0.U1.DUT1.k0 ;
  wire \U0.po00 ;
  wire \U0.po07 ;
  input [9:0] a;
  input [9:0] b;
  output [9:0] r;
  assign \U0.U1.DUT1.k0  = ~(a[6] ^ b[6]);
  assign \U0.po07  = a[6] ^ b[6];
  assign \U0.po00  = a[0] ^ b[0];
  assign r = { 2'h0, \U0.po07 , \U0.U1.DUT1.k0 , 5'h15, \U0.po00  };
endmodule
